name: AAE
target_size: &target_size !!python/tuple [128, 128]
dbatch_size: &dbatch_size 1
checkpoint_path: &checkpoint_path ./weights/23_morphaeus/cxr/
#
# Experiment
#
experiment:
  name: 23_MorphAEus
  task: train # change to test for eval mode only
  weights: #'./weights/23_morphaeus/cxr/AAE/best_model.pt'
#
device: gpu
configurator:
  module_name: core.Configurator
  class_name: DLConfigurator
  params:
#
# Model
#
model:
  module_name: model_zoo.aae_pidhorskyi
  class_name: AAE
  params:
    d: 64
#    extra_layers: 1 # for 64x64
    extra_layers: 2 # for 128x128
    z_dim: 256
#
# Trainer
#
trainer:
  module_name: projects.23_morphaeus.AAETrainer
  class_name: PTrainer
  params:
    input_size: *target_size
    checkpoint_path: *checkpoint_path
    nr_epochs: 500
    loss:
      module_name: optim.losses.ln_losses
      class_name: L2
      params:
    # Optimizer
    optimizer_params:
      lr: 5.0e-4 # 2.03-3 # Orig
  # Data Loader
  data_loader:
    module_name: core.DataLoader
    class_name: DefaultDataLoader
    params:
      args:
        data_dir:
          train:
            - './data/CXR/splits/cxr_normal_train.csv'
          val:
            - './data/CXR/splits/cxr_normal_val.csv'
          test:
            - './data/CXR/splits/cxr_normal_test.csv'
        target_size: *target_size
        batch_size: 128 # orig
#
# Downstream tasks
downstream_tasks:
  pneumonia:
    module_name: projects.23_morphaeus.DownstreamEvaluator
    class_name: PDownstreamEvaluator
    checkpoint_path: *checkpoint_path
    compute_fid: False
    compute_scores: True
    data_loader:
      module_name: core.DataLoader
      class_name: DefaultDataLoader
      params:
        args:
          dataset_module:
            module_name: data.cxr_loader
            class_name: CXRDataset
          target_size: *target_size
          batch_size: *dbatch_size
      datasets:
        Normal_RSNA:
          data_dir:
            test:
              - './data/CXR/splits/cxr_normal_test.csv'
        Pneumonia:
          data_dir:
            test:
              - './data/CXR/splits/cxr_opa_test.csv'
#  covid:
#    module_name: projects.23_morphaeus.DownstreamEvaluator
#    class_name: PDownstreamEvaluator
#    checkpoint_path: *checkpoint_path
#    compute_fid: False
#    compute_scores: True
#    data_loader:
#      module_name: core.DataLoader
#      class_name: DefaultDataLoader
#      params:
#        args:
#          dataset_module:
#            module_name: data.cxr_loader
#            class_name: CXRDataset
#          target_size: *target_size
#          batch_size: *dbatch_size
#      datasets:
#        Normal_Padchest:
#          data_dir:
#            test:
#              - './data/padchest/splits/cxr_normal_test.csv'
#        Covid:
#          data_dir:
#            test:
#              - './data/CXR/splits/cxr_covid_padchest_test.csv'
